config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.views.generic import RedirectView

schema_view = get_schema_view(
       openapi.Info(
          title="First_Project   API",
          default_version='v1',
          description="Test description",
          terms_of_service="https://www.google.com/policies/terms/",
          contact=openapi.Contact(email="contact@snippets.local"),
          license=openapi.License(name="BSD License"),
       ),
       public=True,
       permission_classes=[permissions.AllowAny]
    )

urlpatterns = [
    # Swagger
    path('', RedirectView.as_view(pattern_name='main:index')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # API
    path('api/contact/', include('contact.api.urls')),
    path('api/product/', include('product.api.urls')),

    # django
    path('', include("main.urls", namespace='main')),
    path('contact/', include("contact.urls", namespace='contact')),
    path('about/', include("about.urls", namespace='about')),
    path('product/', include("product.urls", namespace='product')),

    # admin
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from .views import contact_views

app_name = 'contact'

urlpatterns = [
    path('contact/', contact_views, name='contact')
]

main/urls.py
from django.urls import path
from .views import index, investor, project_views, service_views, solution_views

app_name = 'main'

urlpatterns = [
    path('index/', index, name='index'),
    path('investor/', investor, name='investor'),
    path('project/', project_views, name='project'),
    path('service/', service_views, name='service'),
    path('solution/', solution_views, name='solution'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
    </style>
</head>

<body>
    <div class="wrapper">

    {% include 'header.html' %}

        {% block content %}

        {% endblock %}

    {% include 'footer.html' %}

    </div>

    <script src="{% static '/js/script.js' %}"></script>
</body>

</html>

templates/footer.html
{% load static %}
        <footer class="footer">
            <div class="footer__up">
                <a class="footer__logo" href="pages/index.html"><img src="{% static '/images/icons/logofooter.svg' %}" alt=""></a>
                <ul class="footer__list">
                    <h2 class="footer__heading">На сайте</h2>
                    <li class="footer__item"><a class="footer__link" href="pages/aboutUs.html">О нас</a></li>
                    <li class="footer__item"><a class="footer__link" href="pages/solution.html">Решение</a></li>
                    <li class="footer__item"><a class="footer__link" href="pages/service.html">Сервисный центр</a></li>
                    <li class="footer__item"><a class="footer__link" href="pages/ourProjects.html">Наши работы</a></li>
                    <li class="footer__item"><a class="footer__link" href="pages/forInvestors.html">Для инвесторов</a></li>
                    <li class="footer__item"><a class="footer__link" href="pages/contacts.html">Контакты</a></li>
                </ul>
                <ul class="footer__list">
                    <h2 class="footer__heading">Наши продукции</h2>
                    <li class="footer__item"><a class="footer__link" href="#">Солнечные панели</a></li>
                    <li class="footer__item"><a class="footer__link" href="#">Солнечные инверторы</a></li>
                    <li class="footer__item"><a class="footer__link" href="#">Аккумляторная батарея</a></li>
                </ul>
                <ul class="footer__list">
                    <h2 class="footer__heading">Наши контакты</h2>
                    <li class="footer__item"><a class="footer__link" href="#">103445, г. Ташкент, ул. Ш.Арипар, 96А</a>
                    </li>
                    <li class="footer__item"><a class="footer__link" href="#">+998-71-778-78-78 +998-71-788-87-78</a>
                    </li>
                    <li class="footer__item"><a class="footer__link" href="#">info@ies.uz</a></li>
                    <div class="footer__con">
                        <a href="#"><img class="footer__link1" src="{% static 'images/icons/instagram.svg' %}" alt=""></a>
                        <a href="#"><img class="footer__link1" src="{% static '/images/icons/telegram.svg' %}" alt=""></a>
                        <a href="#"><img class="footer__link1" src="{% static '/images/icons/facebook.svg' %}" alt=""></a>
                        <a href="#"><img class="footer__link1" src="{% static '/images/icons/watsup.svg' %}" alt=""></a>
                    </div>
                </ul>
            </div>
            <div class="footer__down">
                <h2 class="footer__down__h2">2023. Все права защищены Solar.uz</h2>
                <h2 class="footer__down__h2">Создание сайта Supersite</h2>
            </div>
        </footer>

templates/header.html
{% load static %}

        <header class="header">
            <nav class="nav">
                <a href="{% url 'main:index' %}" class="nav__logo"></a>
                <ul id="list" class="nav__list nav-links">
                    <li class="nav__item">
                        <a class="nav__link" href="{% url 'about:index' %}">О нас</a>
                    </li>
                    <li class="nav__item">
                        <a class="nav__link" href="{% url 'main:solution' %}">Решение</a>
                    </li>
                    <li class="nav__item">
                        <a class="nav__link" href="{% url 'product:index' %}">Продукция</a>
                    </li>
                    <li class="nav__item">
                        <a class="nav__link" href="{% url 'main:service' %}">Сервисный центр</a>
                    </li>
                    <li class="nav__item">
                        <a class="nav__link" href="{% url 'main:project' %}">Наши работы</a>
                    </li>
                    <li class="nav__item">
                        <a class="nav__link" href="{% url 'main:investor' %}">Для инвесторов</a>
                    </li>
                    <li class="nav__item">
                        <a class="nav__link" href="{% url 'contact:contact' %}">Контакты</a>
                    </li>
                </ul>
                <ul class="nav__lang">
                    <li class="nav__lang1">
                        <img src="{% static '/images/icons/UZ.svg' %}" alt="">
                    </li>
                    <li class="nav__lang1">
                        <img src="{% static '/images/icons/RU.svg' %}" alt="">
                    </li>
                    <li class="nav__lang1">
                        <img src="{% static '/images/icons/ENG.svg' %}" alt="">
                    </li>
                </ul>
                <button id="burger" class="nav__burger">
                    <img src="{% static '/images/icons/burger.svg' %}" alt="">
                </button>
            </nav>
        </header>